org: acidfabric
app: epg
service: epg

provider:
  name: aws
  runtime: dotnetcore2.1
  stage: prod
  region: eu-central-1
  environment:
    AwsConfig__BucketName: ${self:custom.bucket}
    AwsConfig__FileName: ${self:custom.filename}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource:
        Fn::Join: ["", [Fn::GetAtt: [AttachmentsBucket, Arn], "/*"]]

custom:
  stage: ${file(env.configs.yml):stage, self:provider.stage}
  region: ${file(env.configs.yml):region, self:provider.region}
  bucket: ${self:custom.stage}-${file(env.configs.yml):bucket, env:BUCKET_NAME}
  filename: ${file(env.configs.yml):filename, 'Guide'}.xml
  customerExternalIpAddress: ${file(env.configs.yml):customerExternalIpAddress, env:CUSTOMER_EXTERNAL_IP_ADDRESS}/24

package:
  individually: true

functions:
  epgGenerator:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Program
    timeout: 100
    package:
      # artifact: bin/release/netcoreapp2.1/epg.zip
      artifact: epg-package/epg.zip
    events:
      - schedule: cron(0 04 * * ? *)

resources:
  - ${file(Resources/s3-bucket.yml)}
